### ISSUE TITLE
Mute Staffchat

### ISSUE THREAD

**Issue by byZahory** [JJCEDevelopers/UltraStaffChat#3]
**Describe the idea** (Required)
Maybe you can add a feature to do "/sc mute" to stop receiving Staffchat messages, and when you re-use the command, it will unmute it for you so you will receive messages again.

**Additional context** (Required)

**Your full name** (Required for crediting)
Not gonna give my full name, just tag XNMLeroy on Spigot.

**Comment by joshuasing** [comment]
Thank you for the idea!
Will be added in version 2.0.0 :D

**Comment by joshuasing** [comment]
Added in version 2.0.0 that comes out soon.
By the time that you are reading this it might already be out.
