### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by byZahory** [JJCEDevelopers/UltraStaffChat#4]
**Placeholder** (Required)
{color} or {prefix}

**What it displays** (Required)
A configurable color, that can be set using permissions for the user (to show the name in color)

**Why you think the placeholder should be added** (Required)
It would be cool to show the name of a player in color so you can see which rank a user has.

**Real full name** (Used for crediting) (Required)
Just tag @XNMLeroy on SpigotMC

**Moved to***
https://github.com/JoshuaLovesCode/UltraStaffChat/issues/1

**Comment by joshuasing** [comment]
Awesome Idea!
Will be added in version 2.0.0 (Next version)

**Comment by joshuasing** [comment]
Moved. https://github.com/JoshuaLovesCode/UltraStaffChat/issues/1
