### ISSUE TITLE
UltraStaffChat not appearing in BungeeCoord

### ISSUE THREAD

**Issue by Amoneii** [JJCEDevelopers/UltraStaffChat#5]
**UltraStaffChat Version** (Required)
Latest 

**BungeeCord Version** (Required)
Latest

**Java Version** (Not required but recommended)
8

**What happened?**
Basically the plugin doesn't run on the server. Commands also don't appear when typing it.

**Crash Log / Error Log**
`23.11 06:44:21 [Server] INFO [UltraStaffChat] Plugin Starting...
23.11 06:44:21 [Server] WARNING Exception encountered when loading plugin: UltraStaffChat
23.11 06:44:21 [Server] INFO while scanning a quoted scalar
23.11 06:44:21 [Server] INFO in 'reader', line 47, column 8:
23.11 06:44:21 [Server] INFO usage: "&cUsage: /staffchat <message>
23.11 06:44:21 [Server] INFO ^
23.11 06:44:21 [Server] INFO found unexpected end of stream
23.11 06:44:21 [Server] INFO in 'reader', line 47, column 38:
23.11 06:44:21 [Server] INFO ... : "&cUsage: /staffchat <message>
23.11 06:44:21 [Server] INFO ^
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1929)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1843)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1027)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1009)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:394)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124)
23.11 06:44:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)`

**Real full name** (Used for crediting) (Required)
Amonei Robinson

**Comment by joshuasing** [comment]
Thank you for reporting this bug. I am investigating it now.

**Comment by joshuasing** [comment]
@Amoneii This appears to be a configuration problem not a problem with UltraStaffChat.
If you would like help with your config file please send the contents of it in code blocks.
To use code blocks type this:
\`\`\`
<Config File/Code here>
\`\`\`

**Comment by Amoneii** [comment]
,,,
# UltraStaffChat Config File.
# Copyright 2019 Joshua Sing
# Go to https://github.com/JJCEDevelopers/UltraStaffChat/wiki/Config for help with this config!
# Config Version (DO NOT EDIT!!!)
config-version: 10
# Should we notify staff if an update is available? (Recommended!)
announce-update: true
# Should we tell all online staff if another staff member joins?
announce-staff-join: true
# Should we tell all online staff if a staff member leaves?
announce-staff-leave: true
# Should we allow players to toggle there staff chat on/off with /sctoggle?
staffchat-toggle-enabled: true
# Permission to toggle staffchat.
staffchat-toggle-perm: "staffchat.toggle"
# Message sent to the player when the toggle staffchat ON.
staffchat-toggle-message-on: "&f[&lStaffChat&f] &bStaffChat Toggled &fOn&b!"
# Message sent to the player when the toggle staffchat OFF.
staffchat-toggle-message-off: "&f[&lStaffChat&f] &bStaffChat Toggled &fOff&b!"
# Permission to get notified if another staff member joins. (Players with this permission will get notified if another player with this permission joins.)
announce-staff-join-perm: "staffchat.join"
# Staff join message (Placeholders: Player {player})
announce-staff-join-msg: "&7[&f&l+&7] &f{player}"
# Permission to get notified if a staff member leaves. (Players with this permission will get notified if another player with this permission leaves.)
announce-staff-leave-perm: "staffchat.leave"
# Staff join message (Placeholders: Player {player})
announce-staff-leave-msg: "&7[&f&l-&7] &f{player}"
# Update notify permission.
update-announce-perm: "ultrastaffchat.notifyupdate"
# Update notify message. (Placeholders: {newversion} {oldversion})
update-announce-msg: "&8[&c&lUltraStaffChat&8] &cA &cupdate &cis &cavailable! &cCurrent &cversion: &c{oldversion}, &cNew &cversion: &c{newversion}"
# StaffChat Layout (This may not show in console. Placeholders: Player {player}, Server {server}, Message {message}) Note: the placeholders: {player} and {message} are required!
staffchatlayout: "&f[&lStaffChat&f] &b{player}&7: &f{message}"
# StaffChat Message Color code. (Example "&c")
staffchatcolor: "&f"
# Should you be able to use the above prefix to talk in StaffChat? (Only works for players in game! Uses the same permission as the command!)
msg-prefix-send: true
# Message prefix to send message in StaffChat. (Only used if msg-prefix-send: true) Note: cannot be /
msg-prefix: "#"
# Permission to talk in the StaffChat
staffchattalkperm: "staffchat.talk"
# Permission to read StaffChat
staffchatreadperm: "staffchat.read"
# No Permission Message
nopermission: "&cNo Permission."
# Usage Message
usage: "&cUsage: /staffchat <message>
,,,

**Comment by Amoneii** [comment]
I was missing the other ' " ' after "&cUsage: /staffchat. It solved the problem...

**Comment by joshuasing** [comment]
I am glad you were able to figure it out :) 
Sorry I didn't help, I have been busy most of the week.
